gText_Birch_PleaseSetTheTime::
	.string "Errr… What time is it?\n"
	.string "Use {SELECT_BUTTON} to switch clock modes.$"

gText_Birch_IsThisTimeCorrect::
	.string "Is this time correct?$"

gText_Birch_TimeHasBeenSet::
	.string "The time has been set to:\n"
	.string "{STR_VAR_1}, {STR_VAR_2}.$"

gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is CONIFER.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayerMale::
	.string "Hold on!\n"
	.string "You're {PLAYER}{KUN}, my son!\p"
	.string "We live in SUNSET TOWN now,\n"
	.string "remember?\p"
	.string "It's a place in the EURUS REGION.\p"
	.string "$"

gText_Birch_YourePlayerFemale::
	.string "Hold on!\n"
	.string "You're {PLAYER}{KUN}, my daughter!\p"
	.string "We live in SUNSET TOWN now,\n"
	.string "remember?\p"
	.string "It's a place in the EURUS REGION.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
